FROM ubuntu:latest
RUN apt-get update -y 
RUN apt-get install apt-utils vim -y
RUN apt-get install -y python-pip python-dev build-essential -y
RUN apt-get install build-essential libpcre3-dev swig tree -y
CMD ["bash"]

